name: Python tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
            pip install pipenv
            pipenv install --dev
      - name: Lint with ruff
        run: pipenv run ruff check .
      - name: Run tests
        run: pipenv run pytest
